* socialize

  Ever felt lost in a group conversation?
  Have you run out of conversation topics with your friends?
  Don't worry, *socialize* is there to support you.

  It is a self-contained web page which asks socializing, funny and interesting questions.
  Use it as conversation starter or just for fun.

** Installation

   This is just one HTML file, grab the =index.html= and open it in your favourite browser or host it with whatever webserver you like.

   This web page is also available as [[https://nixos.wiki/wiki/Flakes][Nix Flake]].
   The =index.html= file is provided in =/var/www/socialize= of the flake output.
   To use it for example with Nginx, the flakes (here included as =socialize=) content can be accessed like this:

   #+begin_example nix
     services.nginx.virtualHosts."example.org".locations."/".root = "${socialize.packages."<your-arch>".socialize}/var/www/socialize";
   #+end_example

*** Requirements

    The browser must have JavaScript enabled.
    But don't worry, nothing is loaded from a third party.
    
** Adding questions

   Fork this repo, add your questions to the =questions= array in the =index.html= file and submit a pull request :)

** Other application fields

   Even though this is called /socialize/, you can easily realize other things by replacing the question list with appropriate strings:

   - Dice
   - Lottery
   - Fortuneteller
   - ...
